# PyTorch Fundamentals

In [2]:
# !nvidia-smi

In [3]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.5.0


## Introduction to Tensor
### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim # number of dimensions

0

In [7]:
scalar.shape

torch.Size([])

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
[[1, 2], [3, 4]]

[[1, 2], [3, 4]]

In [13]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [ ]:
[[1,2,3], 
[3,6,9], 
[2,4,5]]

In [17]:
# Tensor
tensor = torch.tensor([[[1,2,3], 
                        [3,6,9], 
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
# 2, 3, 3
T = torch.tensor([[[1,2,3], 
[3,6,9], 
[2,4,5]], 
                 [[1,2,3], 
[3,6,9], 
[2,4,5]]])

In [22]:
T.shape

torch.Size([2, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are importanct because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [24]:
# Create a random tensor of size (or shape)

random_tensor = torch.rand(1, 3, 4)

In [23]:
np.random.rand(1, 3, 4)

array([[[0.53843507, 0.83000766, 0.88593447, 0.99201293],
        [0.69442613, 0.74315529, 0.7827205 , 0.56404496],
        [0.96353769, 0.77865792, 0.36328697, 0.0732424 ]]])

In [26]:
random_tensor

tensor([[[0.7287, 0.6528, 0.0677, 0.2656],
         [0.6365, 0.7725, 0.2958, 0.9358],
         [0.6128, 0.4281, 0.1536, 0.4523]]])

In [27]:
random_tensor.ndim

3

In [28]:
random_tensor.shape

torch.Size([1, 3, 4])

### Tensor datatype
**Note**: Tensor datatypes is one of **the 3 big errors** you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not riaht shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [29]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, # What datatype is the tensor (e.g. float32 or float16).
                                                device = None, # Waht decive is your tensor on (cpe, cuda).
                                                requires_grad = False) # Whether or not to track gradient with this tensors operation.
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_32_tensor.device

device(type='cpu')

In [32]:
float_32_tensor.requires_grad

False

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor.dtype

torch.float16

In [35]:
res = float_32_tensor * float_16_tensor

In [36]:
res.dtype

torch.float32

In [37]:
float_32_tensor @ float_32_tensor

tensor(126.)

In [39]:
# float_32_tensor @ float_16_tensor

### Matrix multiplication

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
   - `(3, 3) @ (2, 3)` won't work
   - `(2, 3) @ (3, 4)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
   - `(2, 3) @ (3, 4) -> (2, 4)`
   - `(3, 3) @ (3, 4) -> (3, 4)`

In [40]:
# Create a tensor and add 10 to it.
tensor = torch.tensor([1,2,3])

In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10], 
                         [8, 11], 
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)

In [44]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [47]:
tensor_A.T @ tensor_B

tensor([[ 76, 103],
        [100, 136]])

In [42]:
# @, matmul, mm

In [48]:
# สร้าง tensor_A ขนาด (100, 10) และ tensor_B ขนาด (10, 2)
tensor_A = torch.rand(100, 10)
tensor_B = torch.rand(10, 2)

In [49]:
# หา ขนาดของ res ที่เป็นผลคูณของ tensor_A กับ tensor_B 
res = torch.mm(tensor_A, tensor_B)
res.shape

torch.Size([100, 2])

### Reshaping, stacking, squeezing and unsqueezing Tensors
- `reshape`: reshape an input tensor to a defined shape

In [52]:
np.arange(1, 101, 3)

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [53]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
# Add and extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

- `view`: return a view of an input tensor of certain shape but keep the same memory as the original tensor

In [55]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
# Changing z changes x (because a view of a tensor shares the same menory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

- `stacking`: combine multiple tensor on top of each other (vstack) or side by side (hstack)

In [57]:
# Stack tensors on tep of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

- `squeeze`: removes all `1` dimensions from a tensor

In [59]:
# torch.squeeze() - removes all single dimensions form a target tensor.
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
x_reshaped.shape

torch.Size([1, 9])

In [61]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

- `unsqueuze`: add a `1` dimension to a target tensor

In [62]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
x_unsqueezed.shape

torch.Size([1, 9])

In [64]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
x_unsqueezed

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [65]:
x_unsqueezed.shape

torch.Size([9, 1])

- `permute`: return a view of the input with dimensions permuted (swapped) in a certain way.

In [66]:
# torhc.permute - rearranges the dimensions of a target tensor in a specificed order.
x_original = torch.rand(244, 244, 3) # [height, widht, color_channels]
x_original.shape

torch.Size([244, 244, 3])

In [67]:
# Permute the original tensor to rearrange the axis (or dim) order -> return view of tensor
x_permuted = x_original.permute(2, 0, 1) # shifts axis (0, 1, 2) -> (2, 0, 1) # [color_channels, height, widht]
x_permuted.shape

torch.Size([3, 244, 244])

In [72]:
# ทำการเพิ่ม Dimension ให้กับ tensor A
A = torch.rand(3, 128, 128)
res = torch.unsqueeze(A, dim=0)

In [73]:
res.shape

torch.Size([1, 3, 128, 128])

In [74]:
res = torch.unsqueeze(A, dim=1)
res.shape

torch.Size([3, 1, 128, 128])

In [ ]:
# ทำการสลับ Dimension แรก กับ Dimension สุดท้าย ให้กับ tensorฺ B
B = torch.rand(244, 244, 1)

### Indexing

In [75]:
x_original[0, 0, 0] 

tensor(0.7513)

In [76]:
x_original[0, 0, 0] = 1111

In [77]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1111.), tensor(1111.))

In [78]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [81]:
# Let's index on the most innder bracket (last dimension)
x[0][0][0]

tensor(1)

In [82]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 0]

tensor([[1, 4, 7]])

In [83]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[0, :, 0]

tensor([1, 4, 7])

### PyTorch tensors & NumPy
- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor, want in NumPy -> `torch.Tensor.numpy()`

In [84]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array) #When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise (.type(...))
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
array.dtype

dtype('float64')

In [87]:
tensor.dtype

torch.float64

In [88]:
# Chang the value of array, what will this do `tensor`?
array = array + 1

In [89]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7)

In [91]:
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [92]:
numpy_tensor = tensor.numpy()

In [93]:
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
# สร้าง Tensor Identity matrix จาก numpy
identity_array = np.identity(5)

In [99]:
identity_array.astype(np.float32)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [100]:
identity_tensor = torch.from_numpy(identity_array.astype(np.float32))

In [101]:
identity_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### Running tensors and PyTorch objects on tehe GPUs (and making faster computations)

1. Getting a GPU

In [102]:
# Check gor GPU access with PyTorch
torch.cuda.is_available()

True

In [103]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [104]:
# Count number of devices
torch.cuda.device_count()

1

2. Putting tensors (and models) on GPU

In [105]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device = 'cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [106]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

3. Moveing tensors back to the CPU

In [107]:
# if tensor is on GPU, can't transform it to numpy
# tensor_on_gpu.numpy()

In [109]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)